#ifndef APP_COLORS_H
#define APP_COLORS_H

#include "esp_log.h"

#define COLOR_OK(str) LOG_COLOR(LOG_COLOR_GREEN) str LOG_RESET_COLOR
#define COLOR_WARN(str) LOG_COLOR(LOG_COLOR_BROWN) str LOG_RESET_COLOR
#define COLOR_ERR(str) LOG_COLOR(LOG_COLOR_RED) str LOG_RESET_COLOR
#define COLOR_INFO(str) LOG_COLOR(LOG_COLOR_CYAN) str LOG_RESET_COLOR

#endif