/** #define WS_ON_OPEN 0x00 */
var WS_ON_OPEN = globalThis.WS_ON_OPEN = 0x00
/** #define WS_MSG_ID_ACTUATOR 0x01 */
var WS_MSG_ID_ACTUATOR = globalThis.WS_MSG_ID_ACTUATOR = 0x01
/** #define WS_MSG_ID_CONFIG 0x02 */
var WS_MSG_ID_CONFIG = globalThis.WS_MSG_ID_CONFIG = 0x02
/** #define WS_MSG_ID_SENSOR 0x03 */
var WS_MSG_ID_SENSOR = globalThis.WS_MSG_ID_SENSOR = 0x03
var WS_MSG_ID_LOGIN = globalThis.WS_MSG_ID_LOGIN = 0x04
var WS_MSG_ID_LOGOUT = globalThis.WS_MSG_ID_LOGOUT = 0x05
var WS_MSG_ID_MESSAGE = globalThis.WS_MSG_ID_MESSAGE = 0x06
var WS_MSG_ID_UPDATE_HOSTNAME = globalThis.WS_MSG_ID_UPDATE_HOSTNAME = 0x07
var WS_MSG_ID_UPDATE_SWITCHES = globalThis.WS_MSG_ID_UPDATE_SWITCHES = 0x08

var WS_MSG_ID_WIFI_CONFIG_STA = globalThis.WS_MSG_ID_WIFI_CONFIG_STA = 0x09
var WS_MSG_ID_WIFI_CONFIG_AP = globalThis.WS_MSG_ID_WIFI_CONFIG_AP = 0x0a
var WS_MSG_ID_WIFI_STA_SCAN = globalThis.WS_MSG_ID_WIFI_STA_SCAN = 0x0b
// var WS_MSG_ID_WIFI_AP_UPDATE = globalThis.WS_MSG_ID_WIFI_AP_UPDATE = 0x0c
var WS_MSG_ID_UPDATE_PASSWORD = globalThis.WS_MSG_ID_UPDATE_PASSWORD = 0x0d

var WS_MSG_ID_RESET_CONFIG = globalThis.WS_MSG_ID_RESET_CONFIG = 0x0e
var WS_MSG_ID_RESTART = globalThis.WS_MSG_ID_RESTART = 0x0f

var TCPIP_HOSTNAME_MAX_SIZE = globalThis.TCPIP_HOSTNAME_MAX_SIZE = 32
var APP_NAME_MAX_SIZE = globalThis.APP_NAME_MAX_SIZE = 28;
